blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.list_posts, name='list_posts'),
    path('post<int:pk>', views.post_detail, name='post_detail'),
    path('talia', views.talia_page, name='talia_page')
]

graphics/urls.py
from django.urls import path
from graphics import views


app_name = 'graphics'

urlpatterns = [
    path('', views.list_graphics, name='list_graphics'),
    path('<str:title>/', views.graphic_detail, name='graphic_detail'),
]

sventis_corner/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('graphics/', include('graphics.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-date']


class TaliaText(models.Model):
    content = models.CharField(max_length=140)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content[:20]

    class Meta:
        ordering = ['-id']

graphics/models.py
from django.db import models


class Graphic(models.Model):
    title = models.CharField(max_length=140, unique=True)
    iframe = models.TextField()
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
            return self.title

    class Meta:
        ordering = ['-date']

blog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from . import models


def list_posts(request):
    post_list = models.Post.objects.all()
    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request, 'blog/list_posts.html', {
        'posts': posts,
    })


def post_detail(request, pk):
    return render(request, 'blog/post_detail.html', {
        'post': models.Post.objects.get(pk=pk),
    })


def talia_page(request):
    return render(request, 'blog/talia_page.html', {
        'blurbs': models.TaliaText.objects.all()
    })

graphics/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from graphics import models


def list_graphics(request):
    graphics_list = models.Graphic.objects.all()
    paginator = Paginator(graphics_list, 10)
    page = request.GET.get('page')
    graphics = paginator.get_page(page)
    return render(request, 'graphics/list_graphics.html',
                  {
                      'graphics': graphics
                  })


def graphic_detail(request, title):
    graphic = models.Graphic.objects.get(title=title)
    return render(request, 'graphics/graphic_detail.html',
                  {
                      'graphic': graphic,
                  })

blog/templates/blog/list_posts.html
{% extends 'layout.html' %}
{% block main %}
    <div id='cards' class="mb-4">
        {% for post in posts %}
            <div class='card mb-1'>
                <div class='card-header'>
                    <h3>{{ post.title }}</h3>
                </div>
                <div class='card-body'>
                    <blockquote class='blockquote'>
                        <p class='lead'>{{ post.content|truncatechars:250}}</p>
                        <footer class='blockquote-footer'><small>{{ post.date }}</small></footer>
                    </blockquote>
                    <a href="{% url 'blog:post_detail' post.pk %}" class='btn btn-primary float-right'>Read More</a>
                </div>
            </div>
        {% endfor %}
    </div>

    <nav aria-label='Page navigation'>
        <ul class='pagination justify-content-center'>
            {% if posts.has_previous %}
                <li class='page-item'>
                    <a class='page-link' href='?page={{ posts.previous_page_number }}'>&laquo;</a>
                </li>
            {% endif %}
            <li class='page-item active'>
                <a class='page-link' href='?page={{ posts.number }}'>{{ posts.number }}</a>
            </li>
            {% if posts.has_next %}
                <li class='page-item'>
                    <a class='page-link' href='?page={{ posts.next_page_number }}'>&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>

{% endblock main %}

blog/templates/blog/post_detail.html
{% extends 'layout.html' %}

{% block main %}
  <div class='jumbotron jumbotron-fluid p-4 border border-secondary rounded'>
      <a onclick="window.history.back()" class='btn btn-primary float-right' style='color:white'>&laquo back</a>
      <h1 class='display-4 mb-4'>{{ post.title }}</h1>
      <p class='lead'>{{ post.content|linebreaks }}</p>
      <p><small class='text-muted'>{{ post.date }}</small></p>
  </div>



{% endblock main %}

blog/templates/blog/talia_page.html
{% extends 'layout.html' %}

{% block main %}
    <div class='jumbotron jumbotron-fluid p-4 border border-secondary rounded'>
        <h1>Talia's Nonsense</h1>
        <p>The following are self-proclaimed nicknames that Talia has given herself.</p>
        <ul>
            {% for blurb in blurbs %}
                <li><b>{{ blurb.content }}</b> - <small><em>{{ blurb.date }}</em></small></li>
            {% endfor %}
        </ul>
    </div>



{% endblock main %}

graphics/templates/graphics/graphic_detail.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/graphics/graphic_detail.css' %}">
{% endblock head %}

{% block main %}
    <div id="primary">
        <a onclick="window.history.back()" class='btn btn-primary float-right' style="color:white">&laquo back</a>
        <h1>{{ graphic.title }}</h1>
        <div>{{ graphic.iframe|safe }}</div>
        <p>{{ graphic.description }}</p>
    </div>
{% endblock main %}

graphics/templates/graphics/list_graphics.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/graphics/list_graphics.css' %}">
{% endblock head %}

{% block main %}
    <div id="graphics">
        {% for graphic in graphics %}
            <a href="{% url 'graphics:graphic_detail' graphic.title %}">
                <div class="graphic_card">
                    <h2>{{ graphic.title }}</h2>
                    <p>{{ graphic.description|truncatechars:200 }}</p>
                </div>
            </a>
        {% endfor %}
    </div>

    <nav aria-label='Page navigation'>
        <ul class='pagination justify-content-center'>
            {% if graphics.has_previous %}
                <li class='page-item'>
                    <a class='page-link' href='?page={{ graphics.previous_page_number }}'>&laquo;</a>
                </li>
            {% endif %}
            <li class='page-item active'>
                <a class='page-link' href='?page={{ graphics.number }}'>{{ graphics.number }}</a>
            </li>
            {% if posts.has_next %}
                <li class='page-item'>
                    <a class='page-link' href='?page={{ graphics.next_page_number }}'>&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock main %}

templates/layout.html
{% load staticfiles %}
<!doctype html>
<html lang='en'>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <link rel="icon" href="{% static 'Pingu.png' %}">
    <title>Sventi's Corner</title>

    {% block head %}{% endblock head %}
    {% block style %}{% endblock style %}
</head>
<body class='bg-dark'>
<header>
    <nav class='navbar navbar-expand-md navbar-dark fixed-top' style='background: rgb(40, 40, 50);'>
        <a class='navbar-brand' href={% url 'blog:list_posts' %}>
            <img src="{% static 'Pingu.png' %}" width=30 height=30>
            Sventi's Corner
        </a>
        <button class='navbar-toggler' type='button' data-toggle='collapse'
                data-target='#navbarNav' aria-controls='navbarNav' aria-expanded='false'
                aria-label='Toggle navigation'>
            <span class='navbar-toggler-icon'></span>
        </button>
        <div class='collapse navbar-collapse' id='navbarNav'>
            <ul class='navbar-nav'>
                <li class='nav-item'>
                    <a class='nav-link' href={% url 'blog:list_posts' %}>Home</a>
                </li>
                <li class='nav-item'>
                    <a class='nav-link' href={% url 'graphics:list_graphics' %}>Graphics</a>
                </li>
                <li class='nav-item'>
                    <a class='nav-link' href={% url 'blog:talia_page' %}>Talia's Nonsense</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<main class='container' style='margin-top: 5rem;'>
    {% block main %}{% endblock main %}
</main>
<footer>

</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
</body>
</html>